### ISSUE TITLE
Link to QVF not working

### ISSUE THREAD

**Issue by TinekeDeCat** [danielpilla/qlik-python-sse-churn-model-predictions#1]
Hi Daniel, 

many thanks for your contribution. I am new to using SSE within Qlik, and I like your detailed step-by-step. Unfortunately, the link to the .qvf is not working though, would it be possible to check & replace/add the qvf to download material? 

KR
Tineke

**Comment by danielpilla** [comment]
Hi Tineke,
Thanks for the kind words. And my apologies, I was missing a forward slash in the reference to the qvf. I just moved all of the assets for my repos recently and missed that. Fixed.

Cheers,

**Comment by TinekeDeCat** [comment]
Thx for your prompt reply, Daniel! 
Got the .qvf, thx :) 

Have a nice day!
